[project]
name = "rarita"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fima", email = "loboda.fima@icloud.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
rarita = "rarita:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "services/user",
    "services/product",
    "services/gateway",
]

[tool.uv]
package = false
